[project]
name = "mxr-note2excel"
version = "0.1.0"
description = "一个按照规定格式写记事本，即可转为excel的工具"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "pyinstaller>=6.14.1",
    "pyqt6>=6.9.1",
]
